# è®¾ç½®é…ç½®èŒƒä¾‹ï¼Œå¼€å¯ç¼–è¾‘å™¨çš„è‡ªåŠ¨è¡¥å…¨
"$schema" = 'https://starship.rs/config-schema.json'

# æç¤ºç¬¦
format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$character
"""

right_format = """
$nodejs
"""

# ç¦ç”¨
# $battery
# $username\
# $localip\

# Starship æ‰«ææ–‡ä»¶çš„è¶…æ—¶æ—¶é—´ï¼ˆå•ä½ï¼šæ¯«ç§’ï¼‰ã€‚
scan_timeout = 10

# åœ¨ shell æç¤ºç¬¦ä¹‹é—´æ’å…¥ç©ºè¡Œã€‚
add_newline = false

[directory]
style = "pink"


[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"

# Git

[git_branch]
format = '[$symbol$branch]($style)'
ignore_branches = ["master", "main"]

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_metrics]
format = '[+$added]($added_style)/[-$deleted]($deleted_style)'
added_style = "bold blue"

[git_status]
format = '(\[[$all_status$ahead_behind]($style)\] )'
up_to_date = "[âœ“](bold green)" # è¿œç¨‹
# modified = "ï‘™"
# untracked = "" # æœ‰æ–‡ä»¶æœªæ·»åŠ 
ahead = "â‡¡${count}" # æœªæ¨é€
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"

# right_format

[username]
style_user = "blue bold"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[localip]
ssh_only = false
format = "@[$localipv4](bold green) "
disabled = false

# Env

[nodejs]
format = '[$symbol($version)]($style)'
version_format = "${major}.x"
